### ISSUE TITLE
Issue with scraper main not running 

### ISSUE THREAD

**Issue by sak1997** [sak007/SRIJAS#41]
After running the main project, when I register for a website and then proceed to run the main.py file in the scraper directory, there is an exception that occurs.

Stacktrace:

Athithya@DESKTOP-DM1OEHR MINGW64 ~/Desktop/Classes/CSC510 SE/Project Phase 3/SRIJAS/Code/Scrapper (indeed_scraper)
$ python main.py
{'akashokkumar300@gmail.com': ('Software Developer Intern', 'Raleigh', 'Ashok'), 'sak.animeking@gmail.com': ('Software Engineer Intern', 'Raleigh', 'sak')}
[('akashokkumar300@gmail.com', 'LINKEDIN'), ('sak.animeking@gmail.com', 'INDEED')]
https://www.linkedin.com/jobs/jobs-in-Raleigh?keywords=Software%20Developer%20Intern&f_JT=F%2CP&f_E=1%2C3&position=1&pageNum=0
Traceback (most recent call last):
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Athithya\Desktop\Classes\CSC510 SE\Project Phase 3\SRIJAS\Code\Scrapper\main.py", line 213, in <module>
    run()
  File "C:\Users\Athithya\Desktop\Classes\CSC510 SE\Project Phase 3\SRIJAS\Code\Scrapper\main.py", line 27, in run
    job_map = generate_job_map(job_board_role_mp, all_skills)
  File "C:\Users\Athithya\Desktop\Classes\CSC510 SE\Project Phase 3\SRIJAS\Code\Scrapper\main.py", line 73, in generate_job_map
    j = linkedin_scrapper.get_jobs(rl[0],rl[1],10, all_skills)
  File "C:\Users\Athithya\Desktop\Classes\CSC510 SE\Project Phase 3\SRIJAS\Code\Scrapper\linkedin_scrapper.py", line 25, in get_jobs
    k1 = requests.get(url)
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Athithya\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

Athithya@DESKTOP-DM1OEHR MINGW64 ~/Desktop/Classes/CSC510 SE/Project Phase 3/SRIJAS/Code/Scrapper (indeed_scraper)

**Comment by sak007** [comment]
Fixed
Commit# 2abf033f25fa80298fcbf1c64c31378ac2b53b8c

**Comment by sak1997** [comment]
Fixed now. Good to close this!
